# Generated by Django 2.2 on 2019-04-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
        ('printticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.Order'),
        ),
    ]
