"""
Django settings for JSEPos project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import socket
from configs.settings_common import *

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(('1.1.1.1', 80))
local_ip = s.getsockname()[0]
print('local host IP: ' + local_ip)

if local_ip == "172.17.4.55":
    print('loading prd ...')
    from configs.settings_prd import *
else:
    print('loading dev ...')
    from configs.settings_dev import *
